#!/usr/bin/env node

/**
 * Development Server Startup Script
 * 
 * Interactive setup for local development:
 * - Prompts for configuration values
 * - Creates .env file with settings
 * - Starts the development server
 * 
 * Usage: node start-dev.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { spawn } = require('child_process');
const crypto = require('crypto');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Color codes for terminal output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  cyan: '\x1b[36m'
};

// Questions for setup
const questions = [
  {
    key: 'NODE_ENV',
    question: 'Node environment (development/production): ',
    default: 'development'
  },
  {
    key: 'PORT',
    question: 'Server port: ',
    default: '3000'
  },
  {
    key: 'MONGODB_URI',
    question: 'MongoDB URI: ',
    default: 'mongodb://localhost:27017/projeto-sass'
  },
  {
    key: 'ML_CLIENT_ID',
    question: 'Mercado Livre Client ID (optional): ',
    default: ''
  },
  {
    key: 'ML_CLIENT_SECRET',
    question: 'Mercado Livre Client Secret (optional): ',
    default: ''
  },
  {
    key: 'ML_REDIRECT_URI',
    question: 'Mercado Livre Redirect URI: ',
    default: 'http://localhost:3000/auth/ml-callback'
  },
  {
    key: 'JWT_SECRET',
    question: 'JWT Secret (press Enter to auto-generate): ',
    default: ''
  },
  {
    key: 'FRONTEND_URL',
    question: 'Frontend URL: ',
    default: 'http://localhost:3000'
  }
];

function generateSecret() {
  return crypto.randomBytes(32).toString('hex');
}

function askQuestion(question, defaultVal) {
  return new Promise((resolve) => {
    const displayQuestion = defaultVal 
      ? `${colors.cyan}${question}${colors.reset}[${colors.yellow}${defaultVal}${colors.reset}] `
      : `${colors.cyan}${question}${colors.reset}`;
    
    rl.question(displayQuestion, (answer) => {
      resolve(answer || defaultVal);
    });
  });
}

async function setupEnvironment() {
  console.log(`\n${colors.bright}${colors.blue}🚀 Projeto SASS - Development Setup${colors.reset}\n`);
  
  const config = {};
  
  // Ask all questions
  for (const q of questions) {
    let answer = await askQuestion(q.question, q.default);
    
    // Auto-generate JWT_SECRET if empty
    if (q.key === 'JWT_SECRET' && !answer) {
      answer = generateSecret();
      console.log(`${colors.green}✓ Generated JWT_SECRET${colors.reset}`);
    }
    
    config[q.key] = answer;
  }
  
  rl.close();
  
  // Create .env file in backend directory
  const backendDir = path.join(__dirname, 'backend');
  const envPath = path.join(backendDir, '.env');
  
  // Build env content
  let envContent = '# Generated by start-dev.js\n';
  envContent += `# Generated at: ${new Date().toISOString()}\n\n`;
  
  for (const [key, value] of Object.entries(config)) {
    envContent += `${key}=${value}\n`;
  }
  
  // Write .env file
  try {
    fs.writeFileSync(envPath, envContent);
    console.log(`\n${colors.green}✓ Created ${envPath}${colors.reset}`);
  } catch (err) {
    console.error(`${colors.red}✗ Failed to write .env file: ${err.message}${colors.reset}`);
    process.exit(1);
  }
  
  // Display configuration summary
  console.log(`\n${colors.bright}Configuration Summary:${colors.reset}`);
  console.log(`${colors.cyan}Node Environment:${colors.reset} ${config.NODE_ENV}`);
  console.log(`${colors.cyan}Port:${colors.reset} ${config.PORT}`);
  console.log(`${colors.cyan}MongoDB:${colors.reset} ${config.MONGODB_URI}`);
  if (config.ML_CLIENT_ID) {
    console.log(`${colors.cyan}ML Client ID:${colors.reset} ${config.ML_CLIENT_ID}`);
  }
  console.log(`${colors.cyan}JWT Secret:${colors.reset} ${config.JWT_SECRET.substring(0, 20)}...`);
  
  // Start development server
  console.log(`\n${colors.bright}${colors.green}Starting development server...${colors.reset}\n`);
  
  const child = spawn('npm', ['run', 'dev'], {
    cwd: backendDir,
    stdio: 'inherit',
    shell: true
  });
  
  child.on('error', (err) => {
    console.error(`${colors.red}Failed to start server: ${err.message}${colors.reset}`);
    process.exit(1);
  });
  
  child.on('exit', (code) => {
    console.log(`\n${colors.yellow}Server stopped with exit code ${code}${colors.reset}`);
    process.exit(code);
  });
}

// Run setup
setupEnvironment().catch((err) => {
  console.error(`${colors.red}Setup failed: ${err.message}${colors.reset}`);
  process.exit(1);
});
